language: go

go: 1.10.x

# magic word to use faster/newer container-based architecture
sudo: false

services:
  - docker

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - make test
  - make vet

  # Build and test the Docker image. It's pushed to Docker Hub as part of the
  # deploy phase.
  - docker build -t "$DOCKER_REPO" .
  - docker run -d --name finance-mock-container -p 12111:12111 "$DOCKER_REPO"
  - docker ps -a

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    # Note that currently on the `master` branch is pushed to Docker Hub. We
    # may want to do tagged releases as well if this ends up being something
    # that people use.
    branch: master

notifications:
  email:
    on_success: never


env:
  global:
    - DOCKER_REPO="piquette/finance-mock"
